"""cria tabelas escola

Revision ID: ea67581e531a
Revises: 894a84d282c7
Create Date: 2026-09-07 13:57:16.324311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea67581e531a'
down_revision: Union[str, Sequence[str], None] = '894a84d282c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_disciplina', sa.String(length=255), nullable=False),
    sa.Column('carga', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('regiao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cep')
    )
    op.create_table('tb_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['tb_alunos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['tb_disciplinas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('tb_alunos', 'matricula',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('tb_alunos', 'nome_aluno',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'tb_alunos', ['matricula'])
    op.create_foreign_key(None, 'tb_alunos', 'tb_enderecos', ['endereco_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_alunos', type_='foreignkey')
    op.drop_constraint(None, 'tb_alunos', type_='unique')
    op.alter_column('tb_alunos', 'nome_aluno',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tb_alunos', 'matricula',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('tb_notas')
    op.drop_table('tb_enderecos')
    op.drop_table('tb_disciplinas')
    # ### end Alembic commands ###
